openapi: 3.0.0
info:
  version: 0.0.1
  title: TODO API
  description: 我不知道要寫什麼描述
  termsOfService: terms
  contact:
    name: "Alin"
    url: "https://slides.com/alincode"
    email: "alincode@gmail.com"
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
tags: 
  - name: todo
    description: todo 相關操作
paths:
  /api/todos:
    get:
      description: "取得所有 TODO"
      tags: 
        - todo
      responses:
        '200':
          description: ""